import {useEffect,useRef,useState,type ReactNode} from "react";
import {X,Plus,Trash2,Download,Upload,ArrowUpRight,Check,Puzzle} from "lucide-react";
import {categories,storeFields,type DrawerState,type SellerStore,type Reply} from "../lib/model";
import {exportEnvelope,parseBackup,isExtension} from "../lib/storage";
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog className="modal" ref={ref} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal-header"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="닫기"><X size={18}/></button></div>{children}</dialog>}
export function StoreDialog({data,active,onSave,onClose}:{data:DrawerState;active:string;onSave:(stores:SellerStore[],active:string)=>Promise<boolean>;onClose:()=>void}){
 const[stores,setStores]=useState(()=>structuredClone(data.stores));const[id,setId]=useState(active);const[error,setError]=useState("");const[deleting,setDeleting]=useState(false);const store=stores.find(s=>s.id===id)||stores[0];const[saving,setSaving]=useState(false);
 function change(key:string,value:string){setStores(stores.map(s=>s.id===store.id?{...s,[key]:value}:s));setError("");}
 async function save(){if(stores.some(s=>!s.name.trim())){setError("모든 스토어 이름을 입력해 주세요.");return;}setSaving(true);try{if(await onSave(stores,store.id))onClose();}finally{setSaving(false);}}
 return <Modal title="스토어 설정" onClose={onClose}><p className="modal-intro">한 번 입력한 정보가 답변의 중괄호 자리에 들어가요.</p><div className="store-tabs">{stores.map(s=><button key={s.id} className={s.id===store.id?"active":""} onClick={()=>{setId(s.id);setDeleting(false)}}>{s.name||"새 스토어"}</button>)}<button aria-label="스토어 추가" disabled={stores.length>=100} onClick={()=>{const s={id:crypto.randomUUID(),name:"",channel:"스마트스토어",address:"",exchangeFee:"",returnFee:"",shipping:"",returns:"",size:""};setStores([...stores,s]);setId(s.id);setDeleting(false)}}><Plus size={16}/>추가</button></div><form onSubmit={e=>{e.preventDefault();void save()}}><div className="form-grid"><label className="field">스토어 이름<input required maxLength={100} value={store.name} placeholder="예: 모노리빙" onChange={e=>change("name",e.target.value)}/></label><fieldset className="field channel-field"><legend>판매 채널</legend><div className="segmented">{["스마트스토어","쿠팡","기타"].map(c=><button type="button" key={c} className={store.channel===c?"active":""} onClick={()=>change("channel",c)}>{c}</button>)}</div></fieldset>{storeFields.filter(f=>f.key!=="name").map(f=><label className={`field ${["shipping","address","returns","size"].includes(f.key)?"full":""}`} key={f.key}>{f.label}{["shipping","returns","size"].includes(f.key)?<textarea rows={2} maxLength={4000} value={store[f.key]} placeholder={f.key==="shipping"?"예: 평일 오후 2시 이전 결제 건은 당일 출고됩니다.":f.key==="returns"?"예: 주문 내역에서 교환·반품을 접수해 주세요.":"상품별로 다르면 공통 안내만 입력해 주세요."} onChange={e=>change(f.key,e.target.value)}/>:<input maxLength={4000} value={store[f.key]} placeholder={f.key==="address"?"받는 사람, 우편번호와 주소":"예: 6,000원 (조건을 함께 적어 주세요)"} onChange={e=>change(f.key,e.target.value)}/>}</label>)}</div><p className="form-note">배송비는 고객 변심 기준으로 입력하세요. 상품별로 다른 정보는 답변에서 직접 수정할 수 있어요.</p>{error&&<p role="alert" className="error-text">{error}</p>}<div className="modal-footer">{stores.length>1&&(deleting?<div className="delete-confirm"><span>이 스토어를 삭제할까요?</span><button type="button" onClick={()=>{const rest=stores.filter(s=>s.id!==store.id);setStores(rest);setId(rest[0].id);setDeleting(false)}}>삭제</button><button type="button" onClick={()=>setDeleting(false)}>취소</button></div>:<button type="button" className="danger text-button" onClick={()=>setDeleting(true)}><Trash2 size={15}/>스토어 삭제</button>)}<button type="submit" className="primary push-right" disabled={saving}>{saving?"저장 중…":"스토어 정보 저장"}</button></div></form></Modal>
}
export function ReplyDialog({reply,onSave,onDelete,onClose}:{reply?:Reply;onSave:(reply:Reply)=>Promise<boolean>;onDelete:(id:string)=>Promise<boolean>;onClose:()=>void}){
 const[value,setValue]=useState<Reply>(()=>reply?{...reply}:{id:crypto.randomUUID(),title:"",category:categories[0],body:"",favorite:false});const[saving,setSaving]=useState(false);const[deleting,setDeleting]=useState(false);const bodyRef=useRef<HTMLTextAreaElement>(null);
 async function save(){setSaving(true);try{if(await onSave({...value,title:value.title.trim(),body:value.body.trim()}))onClose();}finally{setSaving(false);}}
 function insert(label:string){const t=bodyRef.current;const start=t?.selectionStart??value.body.length;const end=t?.selectionEnd??start;const token=`{${label}}`;setValue({...value,body:value.body.slice(0,start)+token+value.body.slice(end)});requestAnimationFrame(()=>{t?.focus();t?.setSelectionRange(start+token.length,start+token.length)});}
 return <Modal title={reply?"원본 답변 편집":"새 답변 만들기"} onClose={onClose}><p className="modal-intro">자주 쓰는 문구를 저장하고, 스토어 정보는 자동으로 채우세요.</p><form onSubmit={e=>{e.preventDefault();void save()}}><label className="field">답변 제목<input required maxLength={100} autoFocus value={value.title} placeholder="예: 배송이 지연되고 있어요" onChange={e=>setValue({...value,title:e.target.value})}/></label><fieldset className="field"><legend>문의 분류</legend><div className="segmented wrap">{categories.map(c=><button type="button" key={c} className={c===value.category?"active":""} onClick={()=>setValue({...value,category:c})}>{c}</button>)}</div></fieldset><label className="field">답변 내용<textarea ref={bodyRef} required rows={9} maxLength={12000} placeholder="고객에게 보낼 답변을 입력해 주세요." value={value.body} onChange={e=>setValue({...value,body:e.target.value})}/></label><div className="insert-fields"><span>자동 입력 항목 넣기</span><div>{storeFields.map(f=><button type="button" key={f.key} onClick={()=>insert(f.label)}>{`{${f.label}}`}</button>)}</div></div><label className="checkbox-label"><input type="checkbox" checked={value.favorite} onChange={e=>setValue({...value,favorite:e.target.checked})}/>즐겨찾기에 추가</label><div className="modal-footer">{reply&&(deleting?<div className="delete-confirm"><span>답변을 삭제할까요?</span><button type="button" onClick={async()=>{if(await onDelete(reply.id))onClose()}}>삭제</button><button type="button" onClick={()=>setDeleting(false)}>취소</button></div>:<button type="button" className="danger text-button" onClick={()=>setDeleting(true)}><Trash2 size={15}/>삭제</button>)}<button type="submit" className="primary push-right" disabled={saving||!value.title.trim()||!value.body.trim()}>{saving?"저장 중…":"답변 저장"}</button></div></form></Modal>
}
export function ToolsDialog({data,onImport,onRestore,onClose,notify}:{data:DrawerState;onImport:(data:DrawerState)=>Promise<boolean>;onRestore:()=>Promise<void>;onClose:()=>void;notify:(s:string)=>void}){
 const[pending,setPending]=useState<DrawerState|null>(null);const[error,setError]=useState("");const[connected,setConnected]=useState(false);const[sending,setSending]=useState(false);const timeout=useRef<ReturnType<typeof setTimeout>|null>(null);const requestId=useRef("");const extension=isExtension();
 useEffect(()=>{function listener(e:MessageEvent){if(e.source!==window||e.origin!==location.origin||e.data?.source!=="answer-drawer-extension")return;if(e.data.type==="READY")setConnected(true);if(e.data.type==="SAVED"&&e.data.requestId===requestId.current){if(timeout.current)clearTimeout(timeout.current);setSending(false);e.data.ok?notify("확장프로그램으로 보냈어요."):setError("확장프로그램에 저장하지 못했어요.");}}window.addEventListener("message",listener);if(!extension)window.postMessage({source:"answer-drawer-web",type:"HELLO"},location.origin);return()=>{window.removeEventListener("message",listener);if(timeout.current)clearTimeout(timeout.current)};},[extension,notify]);
 function download(){const blob=new Blob([JSON.stringify(exportEnvelope(data),null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`answer-drawer-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function sync(){requestId.current=crypto.randomUUID();setSending(true);setError("");window.postMessage({source:"answer-drawer-web",type:"SAVE",requestId:requestId.current,data:exportEnvelope(data)},location.origin);timeout.current=setTimeout(()=>{setSending(false);setError("연결을 확인하지 못했어요. 설치 후 이 페이지를 새로고침해 주세요.");},5000);}
 return <Modal title="확장프로그램 · 백업" onClose={onClose}>{!extension&&<><div className="tool-hero"><span className="brand-mark"><Puzzle size={24}/></span><div><h3>문의창 옆에 답변서랍을 열어두세요.</h3><p>저장한 답변을 크롬 사이드 패널에서 꺼내 쓸 수 있어요.</p></div></div><ol className="install-steps"><li><a href="./answer-drawer-extension.zip" download>확장프로그램 ZIP 다운로드 <Download size={15}/></a> 후 압축을 풀어 주세요.</li><li>크롬 주소창에 <code>chrome://extensions</code>를 입력하세요.</li><li><strong>개발자 모드</strong>를 켜고 <strong>압축해제된 확장 프로그램을 로드합니다</strong>에서 압축을 푼 폴더를 선택하세요.</li><li>이 페이지를 새로고침하고 아래 버튼으로 답변을 보내세요.</li></ol><div className="sync-box"><div><strong>{connected?"확장프로그램이 연결됐어요":"설치 후 이 페이지를 새로고침해 주세요"}</strong><p>확장프로그램의 답변을 현재 웹의 내용으로 바꿉니다. 기존 내용은 이전 백업으로 보관해요.</p></div><button className="primary" disabled={!connected||sending} onClick={sync}>{sending?"보내는 중…":"확장프로그램으로 보내기"}</button></div></>}{extension&&<div className="tool-hero"><Puzzle/><div><h3>웹에서도 답변을 관리하세요.</h3><a className="text-button" target="_blank" rel="noreferrer" href="https://ramiteacher.github.io/answer-drawer/">웹사이트 열기 <ArrowUpRight size={15}/></a><p>웹사이트는 배포 후 이용할 수 있어요. 웹과 확장프로그램 간 전송은 직접 실행할 때만 이뤄져요.</p></div></div>}<div className="backup-section"><h3>내 답변 백업</h3><p>답변은 이 브라우저에 저장돼요. 다른 기기에서 쓰거나 브라우저 데이터를 지우기 전 백업해 주세요.</p><div className="backup-actions"><button className="secondary" onClick={download}><Download size={16}/>백업 내보내기</button><label className="secondary file-button"><Upload size={16}/>백업 가져오기<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>2_000_000)throw new Error("2MB 이하 파일을 선택해 주세요.");setPending(parseBackup(await file.text()));setError("");}catch(err){setError(err instanceof Error?err.message:"백업을 읽을 수 없어요.")}e.target.value="";}}/></label><button className="text-button" onClick={()=>void onRestore()}>이전 백업 복원</button></div>{pending&&<div className="import-confirm"><p>스토어 {pending.stores.length}개와 답변 {pending.replies.length}개를 가져올까요? 현재 내용은 이전 백업으로 보관됩니다.</p><div className="backup-actions"><button className="primary" onClick={async()=>{if(await onImport(pending)){setPending(null);notify("백업을 가져왔어요.");}}}>가져오기</button><button className="secondary" onClick={()=>setPending(null)}>취소</button></div></div>}</div>{error&&<p className="error-text" role="alert">{error}</p>}<div className="modal-footer"><button className="secondary push-right" onClick={onClose}>닫기</button></div></Modal>
}
